main: try to fix import collision with cmd
The yardstick cmd module collides with the stdlib cmd module

When invoked from command line python add script directory to
front of sys.path.  This prevents debuggers from importing
cmd and then all fail.

Needs better workaround.

2017-02-13 01:02:33,193 yardstick.orchestrator.heat heat.py:197 DEBUG template object 'demo-59c9699b' created
2017-02-13 01:02:33,193 yardstick.benchmark.contexts.heat heat.py:211 DEBUG start pdb
2017-02-13 01:02:33,194 yardstick.benchmark.contexts.heat heat.py:215 INFO sys.path = ['/home/yardstick/yardstick/yardstick', '/home/yardstick/python', '/home/yardstick/yardstick', '/home/yardstick/yardstick_venv/lib/python2.7', '/home/yardstick_venv/lib/python2.7/plat-x86_64-linux-gnu', '/home/yardstick/
yardstick_venv/lib/python2.7/lib-tk', '/home/yardstick_venv/lib/python2.7/lib-old', '/home/yardstick/yardstick_venv/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/yardstick/yardstick_venv/local/lib/python2.7/site-packages', '/hom
e/yardstick/yardstick_venv/lib/python2.7/site-packages', '/home/yardstick/yardstick/yardstick/yardstick/vTC/apexlake']
Traceback (most recent call last):
  File "/home/yardstick/yardstick/yardstick/benchmark/contexts/heat.py", line 217, in deploy
    import rpdb2; rpdb2.start_embedded_debugger('', True, True)
  File "/home/yardstick_venv/local/lib/python2.7/site-packages/rpdb2.py", line 11297, in <module>
    class CConsoleInternal(cmd.Cmd, threading.Thread):
AttributeError: 'module' object has no attribute 'Cmd'
2017-02-13 01:02:33,222 yardstick.benchmark.runners.base base.py:170 DEBUG Terminating all runners
2017-02-13 01:02:33,222 yardstick.benchmark.runners.base base.py:145 DEBUG Stopping dump process

Change-Id: I8642039b0abf7c435c9774891eb961c846ffc6b2
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>